# Generated by Django 5.1.1 on 2025-05-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_task_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="description",
        ),
    ]
